service: clone-database
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, "intg"}
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  stackName: serverless-clone-database-${opt:stage, "intg"}
  deploymentBucket: serverless-deployment-bucket-${opt:stage, "intg"}
  logRetentionInDays: 30
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds:CreateDBInstance
            - rds:DescribeDBClusters
            - rds:DescribeDBInstances
            - rds:DescribeDBSnapshots
            - rds:ListTagsForResource
            - rds:RestoreDBClusterToPointInTime
            - rds:RestoreDBInstanceFromDBSnapshot
            - rds:RestoreDBInstanceToPointInTime
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - rds:DeleteDBCluster
            - rds:DeleteDBInstance
          Resource:
            - "*"
          Condition:
            StringEquals:
              rds:db-tag/DELETABLE: true
        - Effect: Allow
          Action:
            - rds:DeleteDBCluster
            - rds:DeleteDBInstance
          Resource:
            - "*"
          Condition:
            StringEquals:
              rds:cluster-tag/DELETABLE: true

package:
  exclude:
    - ./**
  include:
    - src/__init__.py

functions:
  planter:
    name: clone-database-planter
    description: run clone database
    handler: src.planter.handler.handle
    memorySize: 128
    timeout: 60
    package:
      include:
        - src/planter/*.py
        - src/planter/*.json
      individually: true
    events:
      - schedule:
          rate: cron(0 16 * * ? *)

  harvester:
    name: clone-database-harverster
    description: stop clone database
    handler: src.harvester.handler.handle
    memorySize: 128
    timeout: 60
    package:
      include:
        - src/harvester/*.py
      individually: true
    events:
      - schedule:
          rate: cron(0 18 * * ? *)

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3
